# Generated by Django 3.0 on 2021-04-15 18:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('messages', models.TextField()),
                ('dt', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
