# Generated by Django 3.1.6 on 2021-03-21 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20210320_1814'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('messages', models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'permissions': [('create_meet', 'can create new meets')]},
        ),
    ]
