# Generated by Django 3.1.6 on 2021-03-21 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20210321_1302'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
