# Generated by Django 3.0 on 2021-04-17 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('chat', '0003_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='meet',
            name='invited',
            field=models.ManyToManyField(related_name='invited_groups', to='accounts.UserProfile'),
        ),
    ]
