# Generated by Django 3.1.6 on 2021-03-21 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='meet',
            name='dt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
