# Generated by Django 3.0 on 2021-04-18 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_meet_invited'),
    ]

    operations = [
        migrations.AddField(
            model_name='meet',
            name='membermeta',
            field=models.TextField(default=''),
        ),
    ]
